### ISSUE TITLE
Registration Email

### ISSUE THREAD

**Issue by LennonConson** [dominiqs81/MIPcc24#1]
There does not seem to be a registration email for the contest located here or on the https://www.mixedinteger.org/2024/index.html

**Comment by dominiqs81** [comment]
You can just send an email to one of the members of the committee. For example, you can find mine here:
https://www.dei.unipd.it/~salvagni/
I will add it to the README though, thanks for raising the point.

**Comment by dominiqs81** [comment]
Done
